
     negatedMetastatement         ::=   "¬"<NO_WHITESPACE>metastatement ;

     metaConjunction              ::=   metastatement "∧" metastatement ;

     metaDisjunction              ::=   metastatement "∨" metastatement ;

     metaImplication              ::=   metastatement "=>" metastatement 

                                    |   statement "=>" metastatement

                                    ;

     metaBiconditional            ::=   metastatement ( "iff" | "<=>" ) metastatement ;

     metaMaterialConditional      ::=   metastatement "->" metastatement ;

     parenthesisedMetastatement   ::=   "(" metastatement ")" ;


     metastatement                ::=   negatedMetastatement
    
                                    |   metaConjunction
     
                                    |   metaDisjunction
     
                                    |   metaImplication
     
                                    |   metaBiconditional
     
                                    |   metaMaterialConditional
     
                                    |   parenthesisedMetastatement
     
                                    ;

 