
     metastatement         ::=   "¬"<NO_WHITESPACE>metastatement
    
                             |   metastatement "∧" metastatement
     
                             |   metastatement "∨" metastatement
     
                             |   metastatement "=>" metastatement
     
                             |   metastatement ( "iff" | "<=>" ) metastatement
     
                             ;

 