
     statement          ::=   "(" statement ")"

                          |   "¬"<NO_WHITESPACE>statement

                          |   statement ( "/\\" | "\\/" | "iff" | "=>" | "<=>" ) statement
 
                          ;

