
     negatedStatement         ::=   "¬"<NO_WHITESPACE>statement ;

     conjunction              ::=   statement "∧" statement ;

     disjunction              ::=   statement "∨" statement ;

     implication              ::=   statement "=>" statement ;

     biconditional            ::=   statement ( "iff" | "<=>" ) statement ;
 
     materialConditional      ::=   statement "->" statement ;


     statement                ::=   negatedStatement

                                |   conjunction
 
                                |   disjunction
 
                                |   implication
 
                                |   biconditional
 
                                |   materialConditional
 
                                ;
